name: Publish to npm

on:
  push:
    tags:
      - '*.*.*'
      - '*.*.*-beta.*'

permissions:
  contents: write
  actions: write

jobs:
  pre-release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.extract_tag.outputs.tag }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          
      - name: Check Branch Checkout
        run: |
          echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "Git status: $(git status)"
          echo "Git log: $(git log -1)"
          
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update npm version
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents: $(ls -la)"
          # Get the current tag and set the package.json version to it
          npm version ${GITHUB_REF_NAME:1} --no-git-tag-version
          # Add some verbosity
          echo "NPM version is now $(npm version)"
          
      - name: Commit the updated package.json
        run: |
          # Add the github user
          git config user.name "GitHub Actions"
          git config user.email "action@github.com"
          
          # Add the package.json
          git add package.json
          git add package-lock.json
          
          # Commit the changes
          git commit -m "Update package.json version"

      - name: Reset the tag to the newest commit
        run: |
          # Delete the previous tag
          git tag --delete ${GITHUB_REF_NAME}
          git push origin :refs/tags/${GITHUB_REF_NAME}
          
          # Create and push the new tag
          git tag ${GITHUB_REF_NAME}
          git push origin --tags
          
      - name: Extract tag name
        id: extract_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > ~/.npmrc
          npm publish
